#request properties
userAgent : Mozilla/5.0
xAuthToken : b821e893b7234fe19c4e754f431b476a

#api properties
apiUrl : http://api.football-data.org
apiVersion : v1

#uri suffixes
competitions : competitions
teams : teams
leagueTable : leagueTable
players : players
matches : fixtures

#filters
matchDayFilter : matchday
availableLeagueIds : 426,430,434,436,438