<%@ taglib uri = "http://java.sun.com/jsp/jstl/core" prefix = "c" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<h2>${league.name}</h2>
<table class="league-table">
  <thead>
  <tr>
    <th>
      Pos.
    </th>
    <th>
      Team
    </th>
    <th>
      P
    </th>
    <th>
      W
    </th>
    <th>
      D
    </th>
    <th>
      L
    </th>
    <th>
      GS
    </th>
    <th>
      GA
    </th>
    <th>
      GD
    </th>
    <th>
      Points
    </th>
  </tr>
  </thead>
  <tbody>
  <c:forEach items="${league.teams}" var="team">
    <tr>
      <td>
          ${team.statistic.position}
      </td>
      <td>
          ${team.name}
      </td>
      <td>
          ${team.statistic.playedGames}
      </td>
      <td>
          ${team.statistic.wins}
      </td>
      <td>
          ${team.statistic.draws}
      </td>
      <td>
          ${team.statistic.losses}
      </td>
      <td>
          ${team.statistic.goalsScored}
      </td>
      <td>
          ${team.statistic.goalsAgainst}
      </td>
      <td>
          ${team.statistic.goalsDifference}
      </td>
      <td>
          ${team.statistic.points}
      </td>
    </tr>
  </c:forEach>
  </tbody>
</table>
